<?php

namespace AppBundle\Repository;

/**
 * ItemCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
